spring:
  application:
    name: dnd
  datasource:
    username: dm
    password: dndpass
    url: jdbc:mysql://localhost:3306/dnd
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: false
  jpa:
    generate-ddl: on
    show-sql: true